apiVersion: apps/v1
kind: Deployment
metadata:
  name: employe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employe
  template:
    metadata:
      labels:
        app: employe
    spec:
      containers:
        - name: employe
          image: depot.dpc.com.tn:8443/beeconstruct/employeservice:v-0.0.80
          ports:
             - containerPort: 8093
---

apiVersion: v1
kind: Service
metadata:
  name: employe
spec:
  selector:
    app: employe
  ports:
    - protocol: TCP
      port: 80          # Exposing service on port 80
      targetPort: 8093  # Targeting container port 8761
  type: LoadBalancer
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: employe-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: beeconstruct-employe.dpc.com.tn
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: employe
              port:
                number: 80  # Matching the service port
  tls:
    - hosts:
        - beeconstruct-employe.dpc.com.tn
      secretName: employe-tls-secret

