apiVersion: apps/v1
kind: Deployment
metadata:
  name: chantier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chantier
  template:
    metadata:
      labels:
        app: chantier
    spec:
      containers:
        - name: chantier
          image: depot.dpc.com.tn:8443/beeconstruct/chantierservice:v-0.0.80
          ports:
            - containerPort: 8097

---




apiVersion: v1
kind: Service
metadata:
  name: chantier
spec:
  selector:
    app: chantier
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 8097  
  type: LoadBalancer
---




apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chantier-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: beeconstruct-chantier.dpc.com.tn
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: chantier
              port:
                number: 80  
  tls:
    - hosts:
        - beeconstruct-chantier.dpc.com.tn
      secretName: chantier-tls-secret



