apiVersion: apps/v1
kind: Deployment
metadata:
  name: offre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: offre
  template:
    metadata:
      labels:
        app: offre
    spec:
      containers:
        - name: offre
          image: depot.dpc.com.tn:8443/beeconstruct/offreservice:v-0.0.80
          ports:
             - containerPort: 8095
---



apiVersion: v1
kind: Service
metadata:
  name: offre
spec:
  selector:
    app: offre
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 8095  
  type: LoadBalancer
---



apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: offre-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: beeconstruct-offre.dpc.com.tn
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: offre
              port:
                number: 80  
  tls:
    - hosts:
        - beeconstruct-offre.dpc.com.tn
      secretName: offre-tls-secret

